var gameSectionStatus = {
  item1: false,
  item2: false,
  item3: false,
  item4: false,
  item5: false,
  item6: false,
  item7: false,
  item8: false,
  item9: false,
}

var winningConditions = [
  {item1: false,
   item2: false,
   item3: false,
   },
  {item4: false,
   item5: false,
   item6: false,
   },
   {item7: false,
   item8: false,
   item9: false,
   },
   {item1: false,
   item4: false,
   item7: false,
   },
   {item2: false,
   item5: false,
   item8: false,
   },
   {item3: false,
   item6: false,
   item9: false,
   },
   {item1: false,
   item5: false,
   item9: false,
   },
   {item3: false,
   item5: false,
   item7: false,
   },
];
